# -*- coding: utf-8 -*-
"""
크롤링 대상 URL 및 설정
"""

# ✅ 크롤링 대상 (장르, 서브장르, URL)
genre_links = [
    ("영화", "드라마", "https://www.tving.com/more/genre/MG100"),
    ("영화", "로맨스", "https://www.tving.com/more/genre/MG130"),
    ("영화", "코미디", "https://www.tving.com/more/genre/MG110"),
    ("영화", "애니메이션", "https://www.tving.com/more/genre/MG240"),
    ("영화", "스릴러", "https://www.tving.com/more/genre/MG140"),
    ("영화", "미스터리", "https://www.tving.com/more/genre/MG150"),
    ("영화", "모험", "https://www.tving.com/more/genre/MG170"),
    ("영화", "액션", "https://www.tving.com/more/genre/MG120"),
    ("영화", "판타지", "https://www.tving.com/more/genre/MG200"),
    ("영화", "SF", "https://www.tving.com/more/genre/MG210"),
    ("영화", "공포", "https://www.tving.com/more/genre/MG160"),
    ("영화", "다큐멘터리", "https://www.tving.com/more/genre/MG250"),
    ("드라마", "미국드라마", "https://www.tving.com/more/genre/POS007"),
    ("드라마", "영국드라마", "https://www.tving.com/more/genre/POS008"),
    ("드라마", "중국드라마", "https://www.tving.com/more/genre/POS005"),
    ("드라마", "일본드라마", "https://www.tving.com/more/genre/POS006"),
    ("드라마", "해외드라마", "https://www.tving.com/more/genre/PCPOS"),
    ("드라마", "로맨스", "https://www.tving.com/more/genre/PCA007"),
    ("드라마", "코미디", "https://www.tving.com/more/genre/PCA020"),
    ("드라마", "판타지", "https://www.tving.com/more/genre/PCA023"),
    ("드라마", "무협", "https://www.tving.com/more/genre/PCAB"),
    ("드라마", "공포", "https://www.tving.com/more/genre/PCAD"),
    ("드라마", "복수", "https://www.tving.com/more/genre/PCA030"),
    ("드라마", "휴먼", "https://www.tving.com/more/genre/PCA024"),
    ("드라마", "범죄 스릴러_수사극", "https://www.tving.com/more/genre/PCA015"),
    ("드라마", "의학", "https://www.tving.com/more/genre/PCA025"),
    ("드라마", "웹툰_소설 원작", "https://www.tving.com/more/genre/PCA028"),
    ("드라마", "정치_권력", "https://www.tving.com/more/genre/PCA034"),
    ("드라마", "법정", "https://www.tving.com/more/genre/PCA036"),
    ("드라마", "청춘", "https://www.tving.com/more/genre/PCA029"),
    ("드라마", "오피스 드라마", "https://www.tving.com/more/genre/PCA040"),
    ("드라마", "사극_시대극", "https://www.tving.com/more/genre/PCA017"),
    ("드라마", "타임슬립", "https://www.tving.com/more/genre/PCA026"),
    ("예능", "버라이어티", "https://www.tving.com/more/genre/PCD005"),
    ("예능", "다큐멘터리", "https://www.tving.com/more/genre/PCT"),
    ("예능", "여행", "https://www.tving.com/more/genre/PCD003"),
    ("예능", "쿡방_먹방", "https://www.tving.com/more/genre/PCD023"),
    ("예능", "연애리얼리티", "https://www.tving.com/more/genre/PCD010"),
    ("예능", "게임", "https://www.tving.com/more/genre/PCD029"),
    ("예능", "토크쇼", "https://www.tving.com/more/genre/PCD011"),
    ("예능", "서바이벌", "https://www.tving.com/more/genre/PCD025"),
    ("예능", "관찰리얼리티", "https://www.tving.com/more/genre/PCD024"),
    ("예능", "스포츠예능", "https://www.tving.com/more/genre/PCD037"),
    ("예능", "교육예능", "https://www.tving.com/more/genre/PCD038"),
    ("예능", "힐링예능", "https://www.tving.com/more/genre/PCD034"),
    ("예능", "아이돌", "https://www.tving.com/more/genre/PCD012"),
    ("예능", "음악서바이벌", "https://www.tving.com/more/genre/PCD027"),
    ("예능", "음악예능", "https://www.tving.com/more/genre/PCD021"),
    ("예능", "코미디", "https://www.tving.com/more/genre/PCD017"),
    ("예능", "가족예능", "https://www.tving.com/more/genre/PCD035"),
    ("예능", "뷰티", "https://www.tving.com/more/genre/PCD022"),
    ("예능", "애니멀", "https://www.tving.com/more/genre/PCD026"),
    ("애니", "키즈", "https://www.tving.com/more/genre/PCC"),
]
